apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: k8-spot-daemon
  name: k8-spot-daemon
  namespace: data-science
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-spot-daemon
  template:
    metadata:
      labels:
        app: k8-spot-daemon
    spec:
      containers:
      - image: 155537346795.dkr.ecr.us-west-2.amazonaws.com/k8-spot-daemon:latest 
        name: k8-spot-daemon
        command:
          - /bin/k8-spot-daemon
          - --autoscalingGroupName
          - prod-kubernetes-data-science-worker-scaling-WorkerASG-1C84ZD5UXRVNX
          - --maxAutoscalingNodes
          - 20
          - --historicalHours
          - 3
          - --regionName
          - us-west-2
          - --maxCV
          - 0.05
          - --minGB
          - 30.0
          - --maxDollarsPerGB
          - 0.01
          - --maxDollarsperCPU
          - 0.03
          - --maxPodKills
          - 20
          - --maxTotalDollarsPerHour
          - 12.0
          - --minMarkupPercentage
          - 10.0
          - --memoryBufferPercentage
          - 5.0
          - --minPriceDifferencePercentage
          - 10.0
          - --updateIntervalSeconds
          - 300
          - --monitor
        ports:
        - containerPort: 8082
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: 50m
            memory: 200Mi
