- cpus: 1
  memory: 1.7
  name: m1.small
- cpus: 1
  memory: 3.75
  name: m1.medium
- cpus: 2
  memory: 7.5
  name: m1.large
- cpus: 4
  memory: 15.0
  name: m1.xlarge
- cpus: 2
  memory: 1.7
  name: c1.medium
- cpus: 8
  memory: 7.0
  name: c1.xlarge
- cpus: 32
  memory: 60.5
  name: cc2.8xlarge
- cpus: 16
  memory: 22.5
  name: cg1.4xlarge
- cpus: 2
  memory: 17.1
  name: m2.xlarge
- cpus: 4
  memory: 34.2
  name: m2.2xlarge
- cpus: 8
  memory: 68.4
  name: m2.4xlarge
- cpus: 4
  memory: 30.5
  name: i2.xlarge
- cpus: 8
  memory: 61.0
  name: i2.2xlarge
- cpus: 16
  memory: 122.0
  name: i2.4xlarge
- cpus: 32
  memory: 244.0
  name: i2.8xlarge
- cpus: 16
  memory: 60.5
  name: hi1.4xlarge
- cpus: 1
  memory: 0.613
  name: t1.micro
- cpus: 1
  memory: 3.75
  name: m3.medium
- cpus: 2
  memory: 7.5
  name: m3.large
- cpus: 4
  memory: 15.0
  name: m3.xlarge
- cpus: 8
  memory: 30.0
  name: m3.2xlarge
- cpus: 8
  memory: 15.0
  name: g2.2xlarge
- cpus: 32
  memory: 60.0
  name: g2.8xlarge
- cpus: 2
  memory: 8.0
  name: m4.large
- cpus: 4
  memory: 16.0
  name: m4.xlarge
- cpus: 8
  memory: 32.0
  name: m4.2xlarge
- cpus: 16
  memory: 64.0
  name: m4.4xlarge
- cpus: 40
  memory: 160.0
  name: m4.10xlarge
- cpus: 64
  memory: 256.0
  name: m4.16xlarge
- cpus: 2
  memory: 3.75
  name: c4.large
- cpus: 4
  memory: 7.5
  name: c4.xlarge
- cpus: 8
  memory: 15.0
  name: c4.2xlarge
- cpus: 16
  memory: 30.0
  name: c4.4xlarge
- cpus: 36
  memory: 60.0
  name: c4.8xlarge
- cpus: 2
  memory: 3.75
  name: c3.large
- cpus: 4
  memory: 7.5
  name: c3.xlarge
- cpus: 8
  memory: 15.0
  name: c3.2xlarge
- cpus: 16
  memory: 30.0
  name: c3.4xlarge
- cpus: 32
  memory: 60.0
  name: c3.8xlarge
- cpus: 4
  memory: 61.0
  name: p2.xlarge
- cpus: 32
  memory: 488.0
  name: p2.8xlarge
- cpus: 64
  memory: 732.0
  name: p2.16xlarge
- cpus: 64
  memory: 976.0
  name: x1.16xlarge
- cpus: 128
  memory: 1952.0
  name: x1.32xlarge
- cpus: 2
  memory: 15.25
  name: r4.large
- cpus: 4
  memory: 30.5
  name: r4.xlarge
- cpus: 8
  memory: 61.0
  name: r4.2xlarge
- cpus: 16
  memory: 122.0
  name: r4.4xlarge
- cpus: 32
  memory: 244.0
  name: r4.8xlarge
- cpus: 64
  memory: 488.0
  name: r4.16xlarge
- cpus: 2
  memory: 15.25
  name: r3.large
- cpus: 4
  memory: 30.5
  name: r3.xlarge
- cpus: 8
  memory: 61.0
  name: r3.2xlarge
- cpus: 16
  memory: 122.0
  name: r3.4xlarge
- cpus: 32
  memory: 244.0
  name: r3.8xlarge
- cpus: 2
  memory: 15.25
  name: i3.large
- cpus: 4
  memory: 30.5
  name: i3.xlarge
- cpus: 8
  memory: 61.0
  name: i3.2xlarge
- cpus: 16
  memory: 122.0
  name: i3.4xlarge
- cpus: 32
  memory: 244.0
  name: i3.8xlarge
- cpus: 64
  memory: 488.0
  name: i3.16xlarge
- cpus: 4
  memory: 30.5
  name: d2.xlarge
- cpus: 8
  memory: 61.0
  name: d2.2xlarge
- cpus: 16
  memory: 122.0
  name: d2.4xlarge
- cpus: 36
  memory: 244.0
  name: d2.8xlarge
