autoscalingGroupName:  prod-kubernetes-data-science-worker-scaling-WorkerASG-1C84ZD5UXRVNX
maxAutoscalingNodes:  20
historicalHours: 3
regionName: us-west-2
maxCV: 0.05
minGB: 30.0
maxDollarsPerGB: 0.01
maxDollarsPerCPU: 0.03
maxPodKills: 20 
maxTotalDollarsPerHour: 12.0
minMarkupPercentage: 10
memoryBufferPercentage: 5
minPriceDifferencePercentage: 10
updateIntervalSeconds: 300 


